---
# Ansible tasks file for mgoodness.ipv6-support

- name: enable IPv6 for existing network interfaces
  sysctl: >
    name=net.ipv6.conf.all.disable_ipv6
    value=0
    ignoreerrors=true
    state=present
  when: ipv6_enabled
  
- name: enable IPv6 for future network interfaces
  sysctl: >
    name=net.ipv6.conf.default.disable_ipv6
    value=0
    ignoreerrors=true
    state=present
  when: ipv6_enabled
  
- name: enable IPv6 in Postfix
  command: postconf -e inet_protocols=all
  when: ipv6_enabled and ipv6_postfix

- name: disable IPv6 for existing network interfaces
  sysctl: >
    name=net.ipv6.conf.all.disable_ipv6
    value=1
    ignoreerrors=true
    state=present
  when: not ipv6_enabled
  
- name: disable IPv6 for future network interfaces
  sysctl: >
    name=net.ipv6.conf.default.disable_ipv6
    value=1
    ignoreerrors=true
    state=present
  when: not ipv6_enabled

- name: disable IPv6 in Postfix
  command: postconf -e inet_protocol=ipv4
  when: not ipv6_enabled and ipv6_postfix
